defaults:
  - sdi_default
  - _self_


resolution: 512
train_batch_size: 1
dataloader_num_workers: 4

dataset_name: render
# dataset_dir: ${oc.env:SCRATCH}/bunny_video_subset
dataset_dir: ${oc.env:SCRATCH}/compositing-outputs/singleimagelightpredictions_outputs/GT_emission_envmap
pretrained_model_name_or_path: ${oc.env:HF_HUB_CACHE}/models--stabilityai--stable-diffusion-2-1/snapshots/5cae40e6a2745ae2b01ad92ae5043f95f23644d6

enable_xformers_memory_efficient_attention: true
vae_type: normal

conditioning_channels: 11

light_parametrization: 'light_bounding_box_3d'

eval:
  device: cuda
  weight_dtype: fp16
  num_inference_steps: 20
  controlnet_model_name_or_path: ${oc.env:SCRATCH}/checkpoints/openrooms_ddim_2024-05-24_10-49-59__6x_data/checkpoint-1034000
  results_dir: ${oc.env:SCRATCH}/results-rot-light/${now:%Y-%m-%d_%H-%M-%S}
  use_rgb_as_diffuse: false
  depth_scale_factor: 1
  obj_color_balance: true
  # shading_maskout_mode: BBox
  # shading_maskout_mode: BBoxWithDepth
  shading_maskout_mode: PointCloud
  # shading_maskout_mode: Cone
  shading_maskout_bbox_dilation: 30
  shading_maskout_bbox_depth_range: 4.0
  # shading_maskout_pc_type: absolute
  # shading_maskout_pc_range: 0.8
  shading_maskout_pc_type: relative
  shading_maskout_obj_dilation: 3
  shading_maskout_cone_radius: 0.6
  point_cloud_fov: 50
  # shading_maskout_pc_above_cropping_type: abovebbox
  shading_maskout_pc_above_cropping_type: argmin
  shading_maskout_cone_angle: 90
  post_compositing: true
  output_all: false

  video_frame_count: 100


light_estimation:
  output_dir: ${oc.env:SCRATCH}/output_light_estimation/${now:%Y-%m-%d_%H-%M-%S}
  backbone_name_or_path: ${oc.env:HF_HUB_CACHE}/models--facebook--convnext-small-224/snapshots/e0df91dcc78dbc0f56be8fbecff706128aee7c28

  train_dataloader_kwargs:
    batch_size: 256
    num_workers: 8
    shuffle: true
    drop_last: true
  
  val_dataloader_kwargs:
    batch_size: 256
    num_workers: 4
    shuffle: false
    drop_last: true
